var GAME_LEVELS = [                                  
  ["                                                                                ",
   "                                                                                ",
   "                                                         x=             x       ",
   "                                                     ~  ~x             =x~  ~   ",
   "                                                         xxxxxxxxxxxxxxxx       ",
   "                        |      |      |        |                             x  ",
   "  x                                                                          x  ",
   "  x       n                                                                  x  ",
   "  x       x      x                                                           x  ",
   "  x              x =                                   x                     x  ",
   "  x              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    x  ",
   "  x              x                                      x                    x  ",
   "  x              x                                       x                   x  ",
   "  x                                                       x     l            x  ",
   "  x                                                   xxxxxxxxxxxxxxxxxx     x  ",
   "  x              x                                    x!!!!!!!!!!!!!!!!x     x  ",
   "  x              x                                    x!!!v!!!!v!!!v!!!x     x  ",
   "  x              x                                                     x    x   ",
   "  x        xxxxxxxxxxx                                                     ~xx  ",
   "  x       xxxxx          x ~ x ~ x ~ xxxx     xxx                          xxx  ",
   "  x      xxxx              x   x   x                                      xxxx  ",
   "  x  @  xxxx                                                             xxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  xxxxxx  ",
   "                                                     x  x  x  x  x   x  x       ",
   "                                                     x!!!!!!!!!!!!!!!!!!x       ",
   "                                                     x!!!!!!!!!!!!!!!!!!x       ",
   "                                                     xxxxxxxxxxxxxxxxxxxx       ",
   "                                                                                ",
   "                                                                                "],
  ["v   v   v   v   v   v   v   v   v   v   v   v | v   v   v   v   v   v | v   v   v   v   v   v   v   v   v   v   v ",
   "                                        |       |           |                   |                                 ",
   "                                                                                                                  ",
   "                                                                                                               x  ",
   "                                                                                                               x  ",
   "                                                         xxx xxx xxx x x xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx  ",
   "                                                                ~           ~               ~       ~       ~     ",
   "                                                                      ~         ~                       ~         ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                  x                                                           x       =           ",
   "             x=            x  =   x        x   =   x      =    x      =    x          =       x =             n   ",
   "           x xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx xxx  ",
   "         x                                                                                                        ",
   " @     x                                         l                                                                ",
   " x    x                                          x                           xxx                x        xxxxx    ",
   " x                                                                          x   x              x  x x x x         ",
   " xx      xxxxxxxx                                     xxxxxxx           xxxx     x            x    ~ ~ ~          ",
   "  xx    xx      x                                    xx      x        xx          xxxxxxxxxxxx                    ",
   "         x      x                                    ~x       x   |  x                                            ",
   "    xxx  x      x ~                            ~xxxxxxx        xxxxxx                                             ",
   "         x      x x   x   xx   xx  x   xx   xxxx                                                                  ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["     x                                                                                                        ",
   "     x               x                                                                                        ",
   "     x    xxx        x                                                                                        ",
   "     x    x x        x                               x                x                                       ",
   "     x    x x        x                               x=              =x                                       ",
   "     x   xx x      xxxxx                             xxxxxxxxxxxxxxxxxx                                       ",
   "     x    x x =    x   x   xx    xxxx                                                                         ",
   "     x    x x     x   lx    x    x                                                                            ",
   "     xx   x xx       xxx xxxx    xxxx         xx                                                              ",
   "     x    x x        x   x          x                                                                         ",
   "     x   xx x=      xx   x          x                                                                         ",
   "     x    x xx       x   xxxxx  xxxxx                xxx                                                      ",
   "     xx   x x        x       x  x!!!!!!!!!!!!!!!!!!!!!!x   ~    xxx                                         n ",
   "     xx  xx         xxxxxxxxxx  xxxxx!!!!!!!!!!!!!!!!!!x       x   xxx     x  xx xxx  xxx  x   xxx   xx   xxxx",
   "          x                         x!!!!!!!!!!!!!!!!!!x       x   x  x   x ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "  @    |  x                         x!!!!!!!!!!!!!!!!!!x       x   x   xxx ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                 xx           ",
   "   xxx   xxx   xx  x   xxx   xxx    xxx  xxxxx  x    x x      xxx  xxxxx xxx  xxx  xx  x   xxx   xx           ",
   "  x     x   x  x x x  x      x  x  x   x   x    x    x x     x   x   x    x  x   x x x x  x      xx           ",
   "  x     x   x  x x x  x  xx  xxx   xxxxx   x    x    x x     xxxxx   x    x  x   x x x x   xxx   xx           ",
   "  x     x   x  x  xx  x   x  x  x  x   x   x    x    x x     x   x   x    x  x   x x  xx      x               ",
   "   xxx   xxx   x  xx   xxx   x  x  x   x   x     xxxx  xxxx  x   x   x   xxx  xxx  x  xx   xxx   xx           ",
   "                                                                                                 xx           ",
   "@                                                                                                             ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
